Добавлена функциональность загрузки фильмов с топ-250 рейтинга imdb. …
kkkyifut/MovieQuiz-ios pull request #4
Opened 2022-10-15 05:49 UTC by kkkyifut

…Добавлен вывод ошибки при отсутствии сети и индикатор загрузки для постеров.

2022-10-15 06:39 UTC, ABashkirova requested changes

2022-10-15 06:39 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +            let randomCondition = self.conditions.randomElement()!
Все же старайтесь не использовать force unwrap'ы. Лучше дать дефолтный параметр:
```suggestion
            let randomCondition = self.conditions.randomElement() ?? "больше"
```

2022-10-15 06:39 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
Здесь вы собираете вопрос. В случае ошибки, постер не будет показан, вместо него – белый экран.
Для пользователя это ошибка – он не сможет правильно ответить на вопрос. Поэтому здесь стоит выйти из функции и предварительно показать ошибку с повтором загрузки.

2022-10-15 06:39 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                case .success(let MostPopularMovies):
camelCase:
```suggestion
                case .success(let mostPopularMovies):
```

2022-10-15 06:39 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                    self.delegate?.didLoadDataFromServer()
К сожалению, API сервиса проектировали очень странно (и так бывает в продакшене странно), и на успешную работу сервиса здесь может вернуться ошибка MostPopularMovies.errorMessage. С ней же придет пустой массив фильмов. И приложение вернет на UI - что все хорошо. Останемся в логическом тупике.

2022-10-15 06:39 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    private var movies: [MostPopularMovie] = []
Давайте придерживаться правила: сначала описываем переменные и константы, затем функции :)

2022-10-15 06:39 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
очень понравилось, что решили в отельной функции с параметром 👍

2022-10-15 06:41 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
Не забудьте вернуть на главный поток вызов ошибки

2022-10-15 07:47 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.delegate?.didFailToLoadData(with: error)
DispatchQueue.main.async { [weak self] in
self?.delegate?.didFailToLoadData(with: error)
}

2022-10-15 07:47 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.delegate?.didFailToLoadData(with: error)
Вызов кода с обновлением UI не с главного потока, может приводить к крашу

2022-10-15 08:15 UTC, kkkyifut commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.delegate?.didFailToLoadData(with: error)
Поправил, спасибо за подсказку :)

2022-10-15 09:54 UTC, merged

2022-11-06 07:37 UTC, kkkyifut commented on MovieQuiz/Services/QuestionFactory.swift
> +            let randomCondition = self.conditions.randomElement()!
@ABashkirova Привет! Кажется, вы забыли оставить комментарии в моём новом PR 😅
https://github.com/kkkyifut/MovieQuiz-ios/pull/5